### PR TITLE
Refactored SVG icons usage

### PR DESCRIPTION
**Pull request by kkomelin**
## Problem/motivation
Currently all SVG icons are manually inlined. The same icon is used up to three times in different places. It increases the amount of data sent to the client and can negatively affect code readability.

## Proposed resolution
Handle SVG icons as modules (React components) and leave everything else to a proper loader.

## Actions taken
1. Extracted SVG icons into __icons__ folder. Please note, this folder is not inside the __public__ folder because we don't want the icons to be public. If you need to move or rename this folder, you may want to adapt the corresponding setting in `next.config.js`. I named the icon files according to their purpose but you may want to rename them to comply with the names in your SVG icon pack.
2. Replaced inline SVG icons with React components which are resolved by the [next-react-svg](https://github.com/jeremybarbet/next-react-svg) plugin.
3. Slightly refactored HTML near the icons in the `pages/index.js`. Nothing big. Just replaced `div` with `span` to correspond with other markup.
4. Used [next-compose-plugins](https://github.com/cyrilwanner/next-compose-plugins) to combine multiple Next plugins.

### CODE REVIEW

**Comment by adamwathan** [comment]
This is cool thanks for this! Ideally I'd like to just pull in our icons via npm (they are all in [this repo](https://github.com/refactoringui/heroicons), I'd just need to publish it) and then import them from node_modules. Any idea how to do that with this plugin? The `include` option seems to get in the way — I'd like to be able to just import anything that ends in `.svg` without having to whitelist a bunch of paths 🤔

**Comment by ajitbohra** [comment]
How about using `svgr` to convert svg into react component or use svgr webpack loader
https://github.com/gregberge/svgr

**Comment by kkomelin** [comment]
@adamwathan The first idea that came to mind is to use Git submodules but it's not very convenient.
I will play with the next-react-svg plugin a little bit more to see if it's possible to achieve the desired behavior.

**Comment by kkomelin** [comment]
@ajitbohra Thanks for the suggestion. I think `gregberge/svgr` can work too. I've chosen next-react-svg because it solves the problem in next-friendly way.

**Comment by kkomelin** [comment]
@adamwathan I looked at the approach which @ajitbohra suggested. It doesn't have that __include__ constraint. I think it should be quite cheap to switch to `gregberge/svgr` because it does pretty much the same. Let me try it.

**Comment by adamwathan** [comment]
You got me playing with this some more and the best solution I've found so far is using `babel-plugin-inline-react-svg`:

https://github.com/airbnb/babel-plugin-inline-react-svg

I actually asked Tim on the Next team and he said this is the best option, so that's cool 👍  Works really well with any SVG file, no matter where it's located in the project 🎉 

I'm going to merge this and layer my commits on top in case you are interested in the difference 👍🏻

**Comment by adamwathan** [comment]
Here's the commit that switches to the babel plugin:

https://github.com/adamwathan/tailwind-jobs/commit/331ef8a9e7dac0a354ef875cdfcc703247a4fde2

**Comment by kkomelin** [comment]
@adamwathan Of course. I just didn't want to add one more config like `.babelrc` to the project. But let's see.

**Comment by adamwathan** [comment]
The SVGR option looks really good too actually 👍

**Comment by kkomelin** [comment]
@adamwathan I actually tried your approach. I didn't work for me for some reason and that `.babelrc`... But Okay, let it be the Babel-way. Thanks for reviewing my PR and working on it even further.

**Comment by adamwathan** [comment]
It didn't work for me either until I disabled `svgo` 😕  But it seems to work after disabling it. Thanks so much for these PRs btw, really cool way for me to learn a bit more about the ecosystem 👍🏻

**Comment by kkomelin** [comment]
It's my pleasure. Planning to adapt your app for my own blog.

**Comment by kkomelin** [comment]
@adamwathan @ajitbohra JFYI, I've just found [gregberge/svgr](https://github.com/gregberge/svgr), a Next wrapper [Anomen/next-svgr](https://github.com/Anomen/next-svgr). Luckily, I searched before writing it myself )
Testing it now. Will let you know if it works.

**Comment by kkomelin** [comment]
Just tested the next-svgr next plugin. It works well. The result is the same. A visible difference is that it's configured through next.config.js instead of .babelrc.

**Comment by adamwathan** [comment]
Nice, just tested it out and I like this solution more as well. Has the added benefit of using the same underlying library that create-react-app uses by default, which just makes the set up feel a little more reliable since a lot of others are depending on it 👍  Switching!

**Comment by kkomelin** [comment]
Good news. Just send the PR for `next-svgr` to upgrade the main dependency https://github.com/Anomen/next-svgr/pull/4

**Comment by ajitbohra** [comment]
yes, the plugin will do the job or else next config can be extended to include the svgr loader.

https://github.com/Anomen/next-svgr/blob/master/src/withSvg.js is extending config to include the loader

similar can be done without depending on the additional dependency https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

**Comment by kkomelin** [comment]
Thanks @ajitbohra. Yes, it's quite easy to implement the same just by adding a few lines to `next.config.js` and directly depend on `@svgr/webpack`, update it whenever you want, etc.
Let's leave it to @adamwathan to decide which approach he prefers.

**Pull request merged**
